### ISSUE TITLE
Conflict between clevertap-cordova and phonegap-plugin-push

### ISSUE THREAD

**Issue by nielsvandenboogaart** [CleverTap/clevertap-cordova#10]
When attempting to use both of these plugins at once they cause a duplicate error in the android.manifest file. the duplicates being:

clevertap-cordova:
1`<uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />`

2`<permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature" />`

3`<receiver android:exported="true" android:name="com.google.android.gms.gcm.GcmReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>`

phonegap-plugin-push:
1`<uses-permission android:name="nl.veiligebuurt.veiligebuurt.permission.C2D_MESSAGE" />`

2`<permission android:name="nl.veiligebuurt.veiligebuurt.permission.C2D_MESSAGE" android:protectionLevel="signature" />`

3`<receiver android:exported="true" android:name="com.google.android.gms.gcm.GcmReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="nl.veiligebuurt.veiligebuurt" />
</intent-filter>
        </receiver>`

**Comment by pwilkniss** [comment]
@nielsvandenboogaart   you could edit the manifest to remove the duplications, but see https://github.com/CleverTap/clevertap-cordova/issues/9
