### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by jmargolese** [CleverTap/clevertap-cordova#11]
I'm getting an error installing the plugin to a V1 Ionic app.
Things looks like they are installed, but the CleverTap object is not defined in the Service where I'm trying to use it, and I get an error that it doesn't exist if I try to inject it into the service.

Any suggestions are welcome. 

> Installing "com.clevertap.cordova.CleverTapPlugin" for ios
> 
> 
> Adding com.clevertap.cordova.CleverTapPlugin to package.json
> 
> 
> Saved plugin info for "com.clevertap.cordova.CleverTapPlugin" to config.xml
> 
> 
> Error: The header content contains invalid characters

**Comment by pwilkniss** [comment]
@jmargolese   not seeing this problem

steps I took:
peter-mac-3:tmp pwilkniss$ ionic start myApp tabs --type ionic1
peter-mac-3:tmp pwilkniss$ cd myApp/
peter-mac-3:tmp pwilkniss$ ionic plugin add https://github.com/CleverTap/clevertap-cordova.git --variable CLEVERTAP_ACCOUNT_ID=bar --variable CLEVERTAP_TOKEN=foo 
build and run xcode proj.  CleverTap is available in JS.
<img width="1022" alt="screen shot 2017-05-22 at 11 58 42 am" src="https://cloud.githubusercontent.com/assets/1172444/26324055/160c2ed8-3ee6-11e7-9594-144c7ab355cc.png">

**Comment by jmargolese** [comment]
Thanks.  I reset everything again and I still get the error on install, but it’s now working for me as well.

I don’t know what, if any harm the install error does.

Thx
