### ISSUE TITLE
Installing CleverTap Ionic plugin with phonegap-plugin-push 1.10.4 ERROR

### ISSUE THREAD

**Issue by aycron-dev** [CleverTap/clevertap-cordova#12]
Hi, this is my first issue reporting... so sorry if I'm not clear...

I've a working app with ionic and CleverTap. When I installed  a newer version of phonegap-plugin-push I had some errors. I removed the CleverTap plugin and all was working.

I needed my push working, so I need the latest version of phonegap-plugin-push.

I run the command 

`ionic plugin add https://github.com/CleverTap/clevertap-cordova.git --save --variable CLEVERTAP_ACCOUNT_ID=<MY ID> --variable CLEVERTAP_TOKEN=<MY TOKEN> --variable GCM_PROJECT_NUMBER=<MY NUMBER>`

and the plugin installs ok, but when I run **cordova prepare** I get some duplicated lines on AndroidManifest.xml.

```
   <receiver android:exported="true" android:name="com.google.android.gms.gcm.GcmReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name=MYAPP />
            </intent-filter>
        </receiver>
```
`  <uses-permission android:name="MYAPP.permission.C2D_MESSAGE" />`

And when I run **ionic build android** I got
```
put:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/MYPATH//platforms/android/AndroidManifest.xml:65:9-71:20 Error:
        Element receiver#com.google.android.gms.gcm.GcmReceiver at AndroidManifest.xml:65:9-71:20 duplicated with element dec
lared at AndroidManifest.xml:46:9-51:20
/MYPATH/platforms/android/AndroidManifest.xml Error:
        Validation failed, exiting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed with multiple errors, see logs
```

**Comment by pwilkniss** [comment]
@aycron-dev see  https://github.com/CleverTap/clevertap-cordova/issues/10

**Comment by harshabonthu** [comment]
@aycron-dev  For now the only option is to fork the clevertap cordova plugin and remove the conflict dependencies from plugin.xml (https://github.com/truckstopmobile/clevertap-cordova/commit/7de8bddd20417c3f547c1322a8b022a00e5573c5)

@pwilkniss One possible solution here would be making the clevertap-cordova plugin to have dependency on Phonegap-push plugin and users would just set the push token using clevertap api methods - All the push notification related events are handled by phonegap-push-plugin.

Editing the android manifest is not an option for cordova apps (I would call it hacky solution, as ideally the platform folders shouldn't be touched in cordova apps)

**Comment by pwilkniss** [comment]
@harshabonthu   if you want to use multiple push providers then yes you will need to manage the conflicts yourself, as you say you can fork and do as you please.

**Comment by aycron-dev** [comment]
Ok, I will try removing the GCM receiver.
