### ISSUE TITLE
CleverTap lib not found in iOS

### ISSUE THREAD

**Issue by renatovieiradesouza** [CleverTap/clevertap-cordova#122]
HI Folks.

I have had some problems on iOS with process build.

My package.json:
```
...
 "@ionic-native/clevertap": "^5.36.0",
"clevertap-cordova": "^2.3.6",
 "clevertap-cordova": {
        "CLEVERTAP_ACCOUNT_ID": "xxxxxx",
        "CLEVERTAP_TOKEN": "xxxxx",
        "CLEVERTAP_REGION": " "
      }
...
```

Here is the crashlog:

```
...platforms/ios/per/Plugins/clevertap-cordova/CleverTapPlugin.m:17:9: fatal error: 
      'CleverTap.h' file not found
#import "CleverTap.h"
```

All the configuration and implementation its the equals documentation.

**Comment by Sonal-Kachare** [comment]
Hi @renatovieiradesouza! Please allow me some time to check this issue, I will update you soon.

**Comment by AishwaryaNanna** [comment]
Hi @renatovieiradesouza , clevertap-cordova working fine for iOS in my project, below are the steps that could help you,

- Install cocoapods (if not done)
- Install pod for iOS project (if not done)
(Note: for M1 machines - if it asks for ffi, run command  _arch -x86_64 gem install ffi --user-install_)
- Remove clevertap-cordova plugin by emptying _your_project/plugin_ folder
- Remove ios project by removing  _your_project/platforms/ios_ folder 
-  Now add clevertap-cordova plugin
- Add iOS platform for your cordova project using command  _cordova platform add ios_ 

Let me know if you have already fixed this or need any help further.

**Comment by darshanclevertap** [comment]
@renatovieiradesouza I hope your problem is resolved. If not, please feel free to reopen this issue.
