### ISSUE TITLE
Including clevertap plugin in ionic2

### ISSUE THREAD

**Issue by shubhanshoo145** [CleverTap/clevertap-cordova#13]
I am trying to include clevertap plugin in my ionic 2 app. I have added the plugin following the given steps but I am not able to refer to the functions in my typescript file. Could someone help me with the import statement? As the export of CleverTap.js is module.exports = new CleverTap().
Thanks in advance

**Comment by pwilkniss** [comment]
@shubhanshoo145   haven't spent much time with ionic 2, but looks like you'd need to create/install a typescript wrapper around the Cordova plugin and they want you doing that via their own plugin repo see https://github.com/ionic-team/ionic-native.

**Comment by aniruddhasm** [comment]
@pwilkniss Can you provide a sample working example in ionic 2

**Comment by pwilkniss** [comment]
@aniruddhasm No. sorry.  As I mentioned above it seems in ionic2 is controlling the plugins they allow, so not really on our radar at the moment.
