### ISSUE TITLE
Add FCM support, since new apps can't use GCM

### ISSUE THREAD

**Issue by masoodusmani** [CleverTap/clevertap-cordova#14]
I tried making the modifications required for FCM to the AndroidManifest.xml, but I got an error: `Android: Warning: GCMNot Registered` when I tried to send a test push notification from the dashboard

**Comment by darshanclevertap** [comment]
Hi Masood,

Could you please tell us which plugin you are using, cordova, ionic or phonegap? Also could you please share the part of your manifest file where you are registering the FCM and GCM Listeners/Receivers.

Thanks!

**Comment by masoodusmani** [comment]
Hi @darshanclevertap, I'm using cordova, and I tried replacing the GCM receiver/services with the FCM ones from the [getting started guide](https://support.clevertap.com/docs/android/getting-started.html) in the plugin.xml, heres the diff: https://gist.github.com/masoodusmani/fe39c3bb42185cc44e0e4ff8424b330c

Here's what it turns into in the manifest:
```xml
<meta-data android:name="CLEVERTAP_NOTIFICATION_ICON" android:value="notification_icon" />
<meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/brand_primary" />
<meta-data android:name="GCM_SENDER_ID" android:value="id:xxxxxxxxx" />
<service android:name="com.clevertap.android.sdk.FcmTokenListenerService">
    <intent-filter>
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
    </intent-filter>
</service>
<service android:name="com.clevertap.android.sdk.FcmMessageListenerService">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>
<meta-data android:name="CLEVERTAP_ACCOUNT_ID" android:value="TEST-XXXXXX" />
<meta-data android:name="CLEVERTAP_TOKEN" android:value="TEST-xxxxxx" />
<activity android:configChanges="orientation|keyboardHidden" android:name="com.clevertap.android.sdk.InAppNotificationActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" />
<receiver android:exported="true" android:name="com.clevertap.android.sdk.InstallReferrerBroadcastReceiver">
    <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER" />
    </intent-filter>
</receiver>
```

**Comment by darshanclevertap** [comment]
Hi, 

Your manifest file seems to be alright. Have you registered with Firebase and created your app on their console? If yes, then please check if you have copied the google-services.json file correctly into your project structure.

Thanks!

**Comment by masoodusmani** [comment]
Yes, I've copied the google-services.json file into the root of my android folder, so it's at the same level as the manifest.

Also, I'm now able to send notifications using the default 1.2.4 release without any firebase libraries, but they're not triggering the `onPushNotification` event on document when I click on the notification, and the 'clicked' number doesn't go up in the clevertap dashboard either. I haven't been able to understand this, but I'm also able to send notifications from the firebase notifications dashboard to the app using the GCM id from the clevertap dashboard (though the title doesn't get sent)

**Comment by darshanclevertap** [comment]
Hi,

Please make sure that the extras which come in the Notification (when you send one from our Dashboard) are passed to the Activity which you are calling. Then only the Push Notification will be captured on our end.

Thanks!

**Comment by masoodusmani** [comment]
Hi, sorry, I'm using cordova, how do I check if the extra data is being sent into the activity? do I have to call something from javascript?

**Comment by masoodusmani** [comment]
In-app notifications seem to show the clicked property correctly though

**Comment by pwilkniss** [comment]
@masoodusmani  the plugin has been updated to use FCM.  You could try uninstalling and reinstalling.

**Comment by masoodusmani** [comment]
That's fantastic! I'll try it out and post an update.

**Comment by masoodusmani** [comment]
Hey, the push notifications work, and I'm getting the payload in the `notification` key in the `onPushNotification` event object. However, the 'Clicked' section of the funnel still doesn't update when I click on a notification sent from a campaign. In-App notifications seem to update the clicked property though. 

Also, I tried this in both singleTask and singleTop launch modes, thinking that `onNewIntent()` wasn't getting called in singleTask mode, but the dashboard doesn't track notification clicks even in singleTop mode.

**Comment by pwilkniss** [comment]
@masoodusmani  please email support at clevertap.com, including your CT account details.  That will be a better channel to get the rest of this resolved for you.  Thanks.

**Comment by pwilkniss** [comment]
@masoodusmani  so our underlying SDK will only record Notification Clicks in the application onActivityCreated callback.  looks like thats not getting called when the app is backgrounded vs launched fresh.

**Comment by masoodusmani** [comment]
Oh, alright then, what do you suggest I do? I'm sending a 'Clicked Push Notification' event in my `onPushNotification` event handler, but it doesn't give that nice 3 step funnel in the campaign report.

**Comment by pwilkniss** [comment]
@masoodusmani   updating the the latest release should solve your issue
