### ISSUE TITLE
Cordova : Single Push Notification Triggered but received twice in the device(that is duplicate notification)

### ISSUE THREAD

**Issue by SudhakarJonakuti** [CleverTap/clevertap-cordova#15]
I am using CleverTap for analytics in the application as per the instructions provided in the official Clevertap Plugin (CleverTap/clevertap-cordova).

For Push Notifications (FCM), I have been using cordova-firebase-plugin (arnesson/cordova-plugin-firebase)

When I add CleverTap to the application the notification are received twice rather than once.
If CleverTap plugin is removed, everything seems to be working Fine.

**Comment by pwilkniss** [comment]
@SudhakarJonakuti   its likely that you have both plugins rendering the notification.

you can try removing on the of the message listeners (either by editing the plugin.xml and reinstalling from your fork, or editing the AndroidManifest directly).

For CleverTap to remove would be:

  <service
                android:name="com.clevertap.android.sdk.GcmMessageListenerService"
                android:exported="false" >
                <intent-filter>
                    <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                </intent-filter>
            </service>

if you run into further problems please drop an email at support at clevertap.com.

**Comment by masoodusmani** [comment]
@pwilkniss I'm interested in this, but there's nothing rendered in your reply between `For CleverTap to remove would be:` and `if you run into further problems`

**Comment by pwilkniss** [comment]
@SudhakarJonakuti @masoodusmani sorry about the bad comment, not sure what happened there.  Anyway the plugin has been updated to use FCM.  You could try uninstalling and reinstalling.  

If you try and use the plugin alongside another push plugin like cordova-plugin-firebase you will run into conflicts that will need to be managed.  The main Android conflict being that you would have 2 FCM message listeners so you will end up with dupe notifications being rendered.  You would need to remove one of the listeners from your AndroidManifest.  If you remove the CleverTap listener, click tracking for notifications sent from CleverTap will not work.  

For example the CleverTap listener looks like this:

--
<service android:name="com.clevertap.android.sdk.FcmMessageListenerService">
  | <intent-filter>
  | <action android:name="com.google.firebase.MESSAGING_EVENT" />
  | </intent-filter>
  | </service>

Its possible to implement your own listener on the native side and then call the relevant underlying SDK to render the notification.
