### ISSUE TITLE
Clevertap push notification not working for IOS

### ISSUE THREAD

**Issue by ftechiesnitin** [CleverTap/clevertap-cordova#18]
I have built an app using IONIC 1 and using CLEVERTAP for analytics and push notification.
For Android, it is working fine but for IOS it is not working. Can anyone help me with this?

https://stackoverflow.com/questions/45549324/clevertap-for-ionic-push-notification-not-working-for-ios

**Comment by pwilkniss** [comment]
@ftechiesnitin  please send an email to support at clevertap.com with your CleverTap account details and more specifics on the issue(s) your having, that will be the best channel to get this resolved for you.

**Comment by ftechiesnitin** [comment]
Thank you @pwilkniss. I have sent a request.

**Comment by ftechiesnitin** [comment]
I have been debugging my app and I found this,

[5577:117049] Value of launch option = (null)

Here the launch option value should not be null. I am not an expert of Objective c. Just curious. I think it is not calling 

registerPush from clevertap.m.

If anyone knows anything about this?

**Comment by pwilkniss** [comment]
@ftechiesnitin not sure I'm following you here.  Please route this through our support with as much detail/debug info as you can and we'll get you sorted out.
