### ISSUE TITLE
 Failed to fetch plugin

### ISSUE THREAD

**Issue by ashishjnvb** [CleverTap/clevertap-cordova#19]
> Error: Failed to fetch plugin https://github.com/CleverTap/clevertap-cordova.git via registry.
 
Probably this is either a connection problem, or plugin spec is incorrect.
 Check your connection and plugin name/version/URL.

* Cordova : 7.0.1
* Ionic: 3.9.2
* NPM : 5.0.4
* Node : v8.1.2

**Comment by pwilkniss** [comment]
@ashishjnvb   are you using the new ionic command ?
The plugin command has been renamed. To find out more, run:

  ionic cordova plugin --help

Examples:

    $ ionic cordova plugin 
    $ ionic cordova plugin add cordova-plugin-inappbrowser@latest
    $ ionic cordova plugin add phonegap-plugin-push --variable SENDER_ID=XXXXX
    $ ionic cordova plugin rm cordova-plugin-camera

this works for me:
ionic cordova plugin add clevertap-cordova@latest --variable CLEVERTAP_ACCOUNT_ID=ACCOUNTID --variable CLEVERTAP_TOKEN=TOKEN

**Comment by GauravPatil29** [comment]
ionic cordova plugin add clevertap-cordova@latest --variable CLEVERTAP_ACCOUNT_ID=ACCOUNTID --variable CLEVERTAP_TOKEN=TOKEN
 even though I use the above command, I have the same issue
