### ISSUE TITLE
Error: Uncaught module com.clevertap.cordova.CleverTapPlugin.CleverTap already defined 

### ISSUE THREAD

**Issue by appplumbr** [CleverTap/clevertap-cordova#2]
I am using the latest master branch of CleverTap plugin.

Ionic project build fails with this error in console:
Uncaught module com.clevertap.cordova.CleverTapPlugin.CleverTap already defined 

I hope the configuration for Hybrid app are same as given for android?

In my Ionic app have added below:

<meta-data  
    android:name="CLEVERTAP_ACCOUNT_ID"  
    android:value="Your CleverTap Account ID"/>  
<meta-data  
    android:name="CLEVERTAP_TOKEN"  
    android:value="Your CleverTap Account Token"/>

<application
    android:name="com.clevertap.android.sdk.Application">

<uses-permission android:name="android.permission.READ_PHONE_STATE"/>

<uses-permission android:name="android.permission.INTERNET"/>

<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

<uses-permission android:name="android.permission.GET_ACCOUNTS"/>

<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

Add an extra line to YOUR_PROJECT/platforms/android/project.properties: cordova.system.library.1=com.google.android.gms:play-services:8.3.0

After I build the app in Android using command line I get the error in device console : 
Uncaught module com.clevertap.cordova.CleverTapPlugin.CleverTap already defined 

I have check the fetch.json/android.json don't see the plugin added twice.

please help?

**Comment by appplumbr** [comment]
My Env: Inonic 1.x, Cordova 5.0.0, Android v23, Support V4

**Comment by pwilkniss** [comment]
@appplumbr the cordova.define wrapper code was inadvertently included in the src CleverTap.js file, that would cause your generated CleverTap.js file to cordova.define the plugin twice.  Its been updated to remove that now.  Should solve this.  Thanks.
