### ISSUE TITLE
Clevertap build errors in combination with phonegap-plugin-push

### ISSUE THREAD

**Issue by ArrowsOff** [CleverTap/clevertap-cordova#20]
Hello,

I've just tried to migrate our app from GCM to FCM including our pushservices from CT. 

Our first setup was as following:
Clevertap-cordova from: https://github.com/truckstopmobile/clevertap-cordova.git (used because the default plugin was creating build errors aswell)
Phonegap-plugin-push

This was all working fine, now since phonegap-plugin-push updated to version 2.0 using FCM I figured we should try this aswell. Installation worked fine, services files are added correctly but the problems start when I start building the app.

> Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.goo
gle.gms.google-services/) or updating the version of com.google.android.gms to 11.0.1. 

This is showing up when I'm building the app, when investigating further I see some version is required: 
> Found com.google.android.gms:play-services-base:+, but version 11.0.1 is needed for the google-services plugin.

Manually updating this version seems impossible since the file is created in the build process. I've tried running with build-extra's.gradle to compile the correct version but no luck so far.

This is completely breaking the build process for me right now and has me reverting back to https://github.com/truckstopmobile/clevertap-cordova.git for now. 

Any idea where this problem is coming from?

**Comment by pwilkniss** [comment]
@ArrowsOff    com.google.android.gms:play-services-base version conflict.  Easiest thing for you to do might be to fork the plugin and edit the plugin xml    https://github.com/truckstopmobile/clevertap-cordova/blob/master/plugin.xml
from <framework src="com.google.android.gms:play-services-base:+" />
to <framework src="com.google.android.gms:play-services-base:11.0.1" />
and install your fork.
