### ISSUE TITLE
Add support for Clevertap iOS SDK 4.2.2

### ISSUE THREAD

**Issue by anandsathe67** [CleverTap/clevertap-cordova#206]
CleverTap iOS SDK 4.2.2 supports XCode 14.3 (Version 4.2 does not - it results in a compilation failure while building an iOS mobile app). Please update the plugin to support Clevertap iOS SDK 4.2.2

**Comment by anandsathe67** [comment]
Thanks @akashvercetti. In case anyone else runs into this issue and wants a workaround, update to clevertap-cordova 2.6.1, modify the Plugin.xml file to point to Clevertap iOS SDK 4.2.2 and use patch_package to generate a patch. No other changes are needed. If there is interest, I can upload the patch file here

**Comment by nishant-clevertap** [comment]
Hi @anandsathe67 

We have added support for CleverTap iOS SDK 4.2.2 in our latest release v2.6.2. Release link: https://github.com/CleverTap/clevertap-cordova/releases/tag/2.6.2
