### ISSUE TITLE
Duplicate google_app_id

### ISSUE THREAD

**Issue by aycron-dev** [CleverTap/clevertap-cordova#23]
Hi,

I'm using this plugin in combination with phonegap-push-plugin 1.10.4.

Installing a new version of clevertap-cordova is generating a duplicate line of  google_app_id

on PROJECT/platforms/android/res/values/strings.xml

   * What went wrong:
        Execution failed for task ':mergeReleaseResources'.
        > /PROJECT /platforms/android/res/values/strings.xml: Error:
        Found item String/google_app_id more than one time

I'm not using push notifications with clever tap.

Thanks!

**Comment by darshanclevertap** [comment]
Hi,

Sorry for the delay in reply. 
If you are not using CleverTap for Push Notifications then I would suggest, you install the clevertap-cordova SDK first and then set up push notifications code like the `google-services.json` and phonegap-push-plugin. You can then exclude the CleverTap code of Push Notifications and use CleverTap to raise analytics events.
Hope this helps!
Reach out to us if you need any help :)

Thanks,
Darshan
CleverTap SDK Engineer
