### ISSUE TITLE
Bug: Push notification callback on Android not triggerd from cold start

### ISSUE THREAD

**Issue by malua** [CleverTap/clevertap-cordova#239]
Hey there,

We just discovered that push notifications in on Android when the App is completely closed won't trigger the `onPushNotification` callback.

This definitely worked in the past and it still works if the App is in the background. But when the app is killed nothing is triggered.

I found this undocumented event `onCleverTapPushNotificationTappedWithCustomExtras` from an old PR https://github.com/CleverTap/clevertap-cordova/pull/89/commits/a5f492168f82c7057685fe398d6cfd168f907a5d, which is connected to the same (but old) issue https://github.com/CleverTap/clevertap-cordova/issues/84.
But it is not triggered as well. 

We haven't changed anything in our setup, still using Capacitor 5 with which it definitely worked. 
We call `ActivityLifecycleCallback.register(this);` in the `CustomApplicationClass`.
```
@Override
  public void onCreate() {
    //Clevertap
    ActivityLifecycleCallback.register(this);

    super.onCreate();
}
```

Do you have any idea what could be the problem?

Thanks and all the best,
Lukas

**Comment by malua** [comment]
Ok I tested with older versions of the clevertap-cordova plugin:

The last version which works is 2.6.2. Starting from 2.7.0 it does not work anymore. So I am pretty sure this is a bug in either the Android SDK or the clevertap-cordova SDK.

**Comment by Anush-Shand** [comment]
@malua This issue wasn’t reproducible on the sample app agnostic of the version. Can the reproduction steps be shared?

**Comment by malua** [comment]
I replied in the support ticket.

**Comment by malua** [comment]
Thank you so much! <3
