### ISSUE TITLE
 GCMMismatchSenderID in cordova phonegap app

### ISSUE THREAD

**Issue by akshgods** [CleverTap/clevertap-cordova#24]
error:  Android: Failed to send out test notification(s)
GCMMismatchSenderID (1).

I'm using phonegap app, in that i used CleverTap.registerPush();
in clevertap.com in user profile  i'm getting wrong Device Token. what i need to do?
i inserted google-services.json in www directory of phoneagp;

is there anything i'm missing?

this code in my push registration. 
` push.on('registration', function(data) {
                    var registration_id = data.registrationId;
                    CleverTap.registerPush();
                });
`
any help

**Comment by darshanclevertap** [comment]
Hi @akshgods

Your `google-services.json` file should be in the `root` directory of your project and not in `www`
Could you please copy the file from `www` to `root` directory of your project and try again?
If you still face any issues, then please do get back to us and we'll help you out :)

**Comment by akshgods** [comment]
@darshanclevertap  
i tried your suggestion,copy the google-services.json file from www to root , but same thing happening . i'm not getting correct value Device Token on website. and same error.
Android: Failed to send out test notification(s)
GCMMismatchSenderID (1).

is there any method so i can send my Device Token id for push notification?

**Comment by darshanclevertap** [comment]
@akshgods 
For Android, the clevertap-cordova SDK automatically sends the device token to our servers. I would suggest, you remove the clevertap plugin, ensure that your google-services.json file is in the root directory and then re-install the plugin. The installation of clevertap-cordova plugin checks for the google-services.json and sends the device token to our servers.
Also are you using FCM or GCM for your push notification service?

**Comment by akshgods** [comment]
@darshanclevertap 
i exactly followed  your all steps, but i'm not getting correct device token on your website. 
same error was throwing.

im using fcm for push.

is there any way to make it from app side, so i can add my token id ? 
can we make it possible so clevertap can get token id what i want to send?.


or do you have any demo code for it?

**Comment by darshanclevertap** [comment]
@akshgods Sorry for the delay. Are you still facing this issue?

**Comment by CHANDRAMOHANnegi** [comment]
Android: Failed to send out test notification(s)
GCMMismatchSenderID (1).

I am facing this issue in react native app , while testing clevertap push  notification , my test user is regirstered for push notification

**Comment by darshanclevertap** [comment]
@CHANDRAMOHANnegi this is the Cordova SDK Github repo, I'd suggest you open an issue in the [React Native Repo here](https://github.com/CleverTap/clevertap-react-native/issues)
