### ISSUE TITLE
IOS Push Notification Alert Issue

### ISSUE THREAD

**Issue by ftechiesnitin** [CleverTap/clevertap-cordova#25]
Hey Guys, I have installed the plugin in my Ionic 1 project for android and IOS. Everything is working properly for android but I don't see the push notification permission alert for IOS. Can anyone help me with this?

**Comment by Aditi3** [comment]
Hey, @ftechiesnitin Can you please check once you have enabled push notifications in your App Settings.

To enable push notifications: Go to App Settings -> Capabilities, if Push Notifications isn’t enabled, click the switch in the Push Notifications section.

Hope this helps.

**Comment by ftechiesnitin** [comment]
Hey, @Aditi3 I have already enabled this option in XCODE. So, I dont think this is an issue. Do you have any other option to solve this issue?

**Comment by Aditi3** [comment]
Hey, Can you try checking you're calling the `CleverTap.registerPush();` from your Javascript?

**Comment by ftechiesnitin** [comment]
@Aditi3 I am doing that too, but still not able to see the alert.

**Comment by ftechiesnitin** [comment]
I tried to debug the code, it seems that 
`document.addEventListener('deviceready', this.deviceReady, false);`
is not trigerring the device ready function.

So, I made the following change,

`        document.addEventListener('deviceready', function () {
          CleverTap.registerPush();
        }, false);`

And now I can see the error while emulating in IOS simulator.

`NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
2017-12-15 20:31:58.551659+0800 TestApp[25756:3569752] Task <3F79FF1E-A3BF-40CF-9E6B-2750EC7E5BCB>.<0> HTTP load failed (error code: -1200 [3:-9802])
2017-12-15 20:31:58.552798+0800 TestApp[25756:3569747] NSURLConnection finished with error - code -1200
2017-12-15 20:32:35.057196+0800 TestApp[25756:3572343] Task <EBE93CC1-A85E-4128-B98D-8F215A32BCDD>.<2> finished with error - code: -1001
2017-12-15 20:32:35.058377+0800 TestApp[25756:3572343] Task <EBE93CC1-A85E-4128-B98D-8F215A32BCDD>.<2> HTTP load failed (error code: -999 [1:89])
`

Is this anything related to the above alert issue?

**Comment by Aditi3** [comment]
Hey, Please add the below snippet code to the `onDeviceReady: function() ` function

`      CleverTap.registerPush();
        CleverTap.setDebugLevel(1);      `

and send us the debug log to get more inside of the error.

**Comment by ftechiesnitin** [comment]
@Aditi3 I solved it by adding fooling lines in .plist file

`
<key>NSAppTransportSecurity</key><dict>  <key>NSExceptionDomains</key>  <dict>    <key>mediaservices.windows.net</key>    <dict>      <key>NSIncludesSubdomains</key>      <true/>      <key>NSExceptionRequiresForwardSecrecy</key>      <false/>    </dict>    <key>cloudvideo.azure.net</key>    <dict>      <key>NSIncludesSubdomains</key>      <true/>      <key>NSExceptionRequiresForwardSecrecy</key>      <false/> </dict></dict>
`

I did not really get it how it started but let's see. I think the issue was with not triggering the `CleverTap.registerPush();`. Thanks for the help.
