### ISSUE TITLE
Ionic 3 build error

### ISSUE THREAD

**Issue by sujitgawas19** [CleverTap/clevertap-cordova#28]
When i run build command - ionic cordova run android --prod, the build fails with following error : 

ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:ttcIndex

FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

This error is basically because of Support Library Packages used by the plugin : 
framework src="com.android.support:support-v4:+" 

if change the version of support library to 
framework src="com.android.support:support-v4:27.+" 
the build works but the plugin is does not work.

Please give proper solution

**Comment by darshanclevertap** [comment]
Hi @sujitgawas19 

We have noted your query and will be releasing a fix soon. Meanwhile if you change the version of the support library to `com.android.support:support-v4:26.1.0` , the plugin will work. Our plugin is not updated to support Android support libraries 27 & above. 

Thanks!

**Comment by sujitgawas19** [comment]
I also had to change the version of Google Actions, Base Client Library and firebase messaging APIs.
framework src="com.google.firebase:firebase-messaging:11.+" 
framework src="com.google.android.gms:play-services-base:11.+"

because using the latest versions (i.e. 12.0.0) of these APIs was giving following error : 
Error: more than one library with package name com.google.android.gms.license

i was able to make the android build successfully but the plugin still doesn't work.

Please help

**Comment by sujitgawas19** [comment]
@darshanclevertap 
Can you please provide some solution to the above query??

**Comment by darshanclevertap** [comment]
@sujitgawas19 We have updated the plugin for Ionic3 support. Check out the latest release/commit.
