### ISSUE TITLE
cannot find symbol getView() in cordova 6.0.0

### ISSUE THREAD

**Issue by sulabh** [CleverTap/clevertap-cordova#3]
After upgrading cordova to cordova 6.0.0. the plugin stopped compiling. It throws an error : 

    [javac] ...../platforms/android/src/com/clevertap/cordova/CleverTapPlugin.java:592: error: cannot find symbol
    [javac]         webView.getView().post(new Runnable() {
    [javac]                ^
    [javac]   symbol:   method getView()
    [javac]   location: variable webView of type CordovaWebView

Please resolve

**Comment by pwilkniss** [comment]
@sulabh can't replicate with Cordova 6.1.1/Android 5.1.1.  Can you provide more info ?
