### ISSUE TITLE
Add Android O Channel Documentation

### ISSUE THREAD

**Issue by stevecarlton** [CleverTap/clevertap-cordova#30]
I see that the plugin support channels for Android O but this is not documented anywhere that I could find and is not included in the example project.

**Comment by darshanclevertap** [comment]
Hi @stevecarlton 
Thank you for pointing this out, we will be updating our documentation soon. Meanwhile you can use the following - 

```
CleverTap.createNotificationChannel("cordovaId","Cordova Channel","Cordova Android O Channel",4,true);
CleverTap.createNotificationChannelGroup("groupId","First Group");
CleverTap.createNotificationChannelWithGroupId("channelId","First Channel","First Channel in First Group",1,"groupId",true);
CleverTap.deleteNotificationChannel("cordovaId");
```

`createNotificationChannel` requires the following parameters -
Channel ID - "cordovaId" (As per the above example)
Channel Name - "Cordova Channel"
Channel Description - "Cordova Android O Channel"
Channel Importance - 3 (Default) , 4(High), 5 (Max)
Badge display - true or false

`createNotificationChannelGroup` requires the following parameters - 
Group ID - "groupId" (As per the above example)
Group Name - "groupName"

`createNotificationChannelWithGroupId` requires the following parameters -
Channel ID - "channelId" (As per the above example)
Channel Name - "First Channell"
Channel Description - "First Channel in First Group"
Channel Importance - 3 (Default) , 4(High), 5 (Max)
Group ID - "groupId"
Badge display - true or false

`deleteNotificationChannel` requires only the channel id as its parameter.

Hope this helps you. :)
