### ISSUE TITLE
[Question] Clevertap Cordova With Ionic V1

### ISSUE THREAD

**Issue by ebellumat** [CleverTap/clevertap-cordova#33]
How to configure the iOnic V1 App to use CleverTap? I have to configure AndroidManifest.xml and info.plist Manually? How can i start the service from app.js on DeviceReady?

**Comment by darshanclevertap** [comment]
@ebellumat Sorry for the delay in reply. But have you tried following our installation instructions in the [README](https://github.com/CleverTap/clevertap-android-sdk/blob/master/README.md)? Our library is compatible with all Ionic versions.

**Comment by darshanclevertap** [comment]
@ebellumat If you are still facing any issues, please reach out support@clevertap.com. I'm closing this issue for now

**Comment by ebellumat** [comment]
I Already made the integration with Ionic V1, thanks for your time.
