### ISSUE TITLE
Not working on Cordova 9

### ISSUE THREAD

**Issue by malua** [CleverTap/clevertap-cordova#35]
This plugin is not working on cordova 9 due to this:

> Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

I already provided a pull request

**Comment by darshanclevertap** [comment]
Thank you for pointing this out. We will be updating our library for Cordova 9 in the next release. I will look into your PR then and merge it if required.

**Comment by malua** [comment]
hey, thanks for the information! i just wanted to ask if there is a timeline for the update?

**Comment by malua** [comment]
Because in november google is requiring a higher android sdk which is, as far as i know only supported by cordova 9

**Comment by darshanclevertap** [comment]
@malua We now have support for Cordova 9. Check out our last release.

**Comment by malua** [comment]
unfortunately it does not work. you can't even install the plugin correctly.

as "context.require" is wrong in androidAfterPluginAdd.js. When you install the pugin you get a 

> context.require is not a function

so nothing from the afterplugin script gets added. 

you need to loose the context. and just use require as you can see in my pull request.

**Comment by darshanclevertap** [comment]
@malua Missed this when updating to Cordova 9. We'll be fixing this soon in the next release.

**Comment by darshanclevertap** [comment]
Closing this as the latest version supports Cordova 9
