### ISSUE TITLE
google json conflicts & not working for cordova 9

### ISSUE THREAD

**Issue by kaushalkishore1** [CleverTap/clevertap-cordova#36]
it is supposed that blank JSON is not required in a plugin which leads to conflicts with existing google JSON file present in the project, issues with Cordova 9 :
Using "requireCordovaModule" to load the non-Cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

**Comment by darshanclevertap** [comment]
Hi @kaushalkishore1 

Thank you for your suggestions, currently, our Cordova SDK is not compatible with Cordova 9. We are working on this and will release a new version compatible with Cordova 9 in the coming week.

**Comment by darshanclevertap** [comment]
@kaushalkishore1 We have now support for Cordova 9. Please check out our last release.
