### ISSUE TITLE
Feature request: Set Android Push Icon Accent Color / Small and Big Icon

### ISSUE THREAD

**Issue by malua** [CleverTap/clevertap-cordova#4]
Hello,

thanks for your hard work on a cordova integration.
I am missing a few customizations on the android platform.

Looking at the description of this cordova plugin [npm.js urbanairship](https://www.npmjs.com/package/urbanairship-cordova), it looks like it is possible to change the accent color and set the small and big icon. but obviously you would have to integrate that in your sdk. 

```
 <!-- Override the Android notification icon -->
 <preference name="com.urbanairship.notification_icon" value="ic_notification" />

 <!-- Override the Android notification large icon -->
 <preference name="com.urbanairship.notification_large_icon" value="ic_notification_large" />

 <!-- Specify the notification accent color for Android API 21+ (Lollipop) -->
 <preference name="com.urbanairship.notification_accent_color" value="#0000ff" />
```

maybe you can let me know, if that is something you are planning?
thank you very much.

**Comment by pwilkniss** [comment]
@malua  our SDK supports setting the small icon.  for now, if you want you can edit your AndroidManifest.xml like so:

<meta-data
    android:name="CLEVERTAP_NOTIFICATION_ICON"
    android:value="ic_stat_red_star"/> 

We'll get it on the road map to add to the plugin formally.  Thanks.

**Comment by malua** [comment]
yes i knew about the small icon. should have clarified that i am missing the other two. Large icon isn't that important, because android uses the app icon by default, but the accent color would be nice. anyways, thanks for fast response!
