### ISSUE TITLE
Default events not getting recorded

### ISSUE THREAD

**Issue by sanju1993** [CleverTap/clevertap-cordova#42]
Hello,

in  android , default clevertap events are not getting recorded. All the custom events are working fine. 

Also in Clever campaigns, Welcome email is not getting sent to android users. Everything works fine for iOS app.

Please guide us in resolving this issue.

my environment details are as follows -
Ionic Framework  : ionic-angular 3.9.2  
@ionic/app-scripts : 3.2.3
cordova (Cordova CLI) : 8.0.0
NodeJS            : v6.9.0 
  npm               : 6.6.0
  OS                : Linux 4.15

**Comment by Aditi3** [comment]
Hi @sanju1993 

We will be needing CleverTap logs to check the issue here.

Hence, request you to enable the CleverTap Debug log and share it with us on email support@clevertap.com?

Code snippet to enable Debug log

`CleverTap.setDebugLevel(3);`

Thank you.
