### ISSUE TITLE
config file undefined requested for changes, on cordova 9

### ISSUE THREAD

**Issue by eidanfi** [CleverTap/clevertap-cordova#44]
hi, when i try to install the cleverTap-cordova plugin on my ionic 3 project, i got this error:

Installing "clevertap-cordova" for android
**config file undefined requested for changes not found** at /Users/--/Projects/--/platforms/android/undefined, ignoring
Subproject Path: CordovaLib
Subproject Path: app
Installing "clevertap-cordova" for ios
**config file undefined requested for changes not found** at /Users/--/Projects/--/platforms/ios/undefined, ignoring
Adding clevertap-cordova to package.json
context.require is not a function

**Comment by darshanclevertap** [comment]
Hi @eidanfi 

Are you able to proceed or our package fails to get added to your project?

**Comment by malua** [comment]
I also have the config file undefined errors, but they have existed for a very long time, and don't have real consequences as far as i can tell.

> context.require is not function

on the other hand breaks the plugin installation. more information can be found here:
https://github.com/CleverTap/clevertap-cordova/issues/35#issuecomment-572944290

**Comment by eidanfi** [comment]
> Hi @eidanfi
> 
> Are you able to proceed or our package fails to get added to your project?

package fails to get added to my project

**Comment by darshanclevertap** [comment]
@eidanfi We will fix this in the next release. Closing this issue as it's not a blocker in building your code.
