### ISSUE TITLE
Plugin methods don't work correctly

### ISSUE THREAD

**Issue by eidanfi** [CleverTap/clevertap-cordova#47]
Hello, I'm using yours plugin (version 2.1.6) with Ionic3 (cordova 9) and I'm trying to initialize the plugin.
the problem is that any method that I'm trying to call to from my app component isn't fulfilled, if I'm putting await the script got blocked and nothing happened.

i'm still getting this warnings on installation process: 

config file undefined requested for changes not found at /Users/--/Projects/cleverTap/platforms/android/undefined, ignoring
Subproject Path: CordovaLib
Subproject Path: app
Uninstalling clevertap-cordova from ios
config file undefined requested for changes not found at /Users/--/Projects/cleverTap/platforms/ios/undefined, ignoring

**Comment by darshanclevertap** [comment]
Can you please help with what command are you trying to install the plugin?

**Comment by eidanfi** [comment]
ionic cordova plugin add clevertap-cordova@latest --variable CLEVERTAP_ACCOUNT_ID="****" --variable CLEVERTAP_TOKEN="*****"

**Comment by eidanfi** [comment]
> Can you please help with what command are you trying to install the plugin?

ionic cordova plugin add clevertap-cordova@latest --variable CLEVERTAP_ACCOUNT_ID="****" --variable CLEVERTAP_TOKEN="*****"

**Comment by darshanclevertap** [comment]
@eidanfi Please allow me some time to try and recreate this issue. I will keep you updated

**Comment by darshanclevertap** [comment]
@eidanfi For ionic 3 can you try the following command - 

`npm install @ionic-native/clevertap --save `

Let me know if this also doesn't work for you

**Comment by eidanfi** [comment]
> For ionic 3 can you try the following command -
> 
> `npm install @ionic-native/clevertap --save `
> 
> Let me know if this also doesn't work for you

of-course i did it, otherwise i couldn't  use it inside ionic. what you have suggested it's only communication between ionic/angular and the cordova plugin.
for ionic 3 it is: npm install @ionic-native/clevertap@4 --save

**Comment by kumaratulismu** [comment]
@eidanfi Closing this as the integration was sorted. Please let me know if we you face any issues.

**Comment by juliansand** [comment]
im having the same issue, but only with android. Im using ionic 3 and no method responds on android.
