### ISSUE TITLE
No record for key [category#${applicationId}]

### ISSUE THREAD

**Issue by sandeshbsuvarna** [CleverTap/clevertap-cordova#5]
Error while building the project. Error Execution failed for task ':processDebugManifest'.
> No record for key [category#${applicationId}]

**Comment by pwilkniss** [comment]
@sandeshbsuvarna  what version of Cordova?  can you please provide steps to reproduce thanks

**Comment by sandeshbsuvarna** [comment]
Cordova -v : 6.3.1
cordova platform version: android 5.2.2

Steps to reproduce: Just installed the plugin using below command
ionic plugin add https://github.com/CleverTap/clevertap-cordova.git --variable CLEVERTAP_ACCOUNT_ID=YOUR CLEVERTAP ACCOUNT ID --variable CLEVERTAP_TOKEN=YOUR CELVERTAP ACCOUNT TOKEN --variable GCM_PROJECT_NUMBER=YOUR GCM PROJECT NUMBER


I can see these on my android manifest.xml
<uses-permission android:name="${applicationId}.permission.C2D_MESSAGE"/>

<intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
        <category android:name="${applicationId}"/>
</intent-filter>

<permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature"/>

**Comment by pwilkniss** [comment]
@sandeshbsuvarna   replace the placeholders with your actual string values so they end up as strings in your AndroidManifest.xml.

e.g. for example
<meta-data
            android:name="CLEVERTAP_ACCOUNT_ID"
            android:value="RZ5-R9K-554Z" />;
        <meta-data
            android:name="CLEVERTAP_TOKEN"
            android:value="3c2-512" />

Closing this here.  Please drop a line to support@clevertap.com if you need further help.

**Comment by sandeshbsuvarna** [comment]
i am not a stupid. I did change the values while executing the ionic plugin command on CLI
