### ISSUE TITLE
2.1.7 - com.android.installreferrer Causing Additional Permissions To Be Added

### ISSUE THREAD

**Issue by hvaughan3** [CleverTap/clevertap-cordova#50]
The recent [updates in 2.1.7](https://github.com/CleverTap/clevertap-cordova/commit/5bad22fd260ecd4a2f3a0804ab6e006697b1e89b) added a dependency to `com.android.installreferrer` 1.1. According to the link below this dependency has a bug in it which leads to the addition of several new permissions when building on Android because installreferrer is missing a `minSdkVersion`. Permissions include:

WRITE_EXTERNAL_STORAGE
READ_EXTERNAL_STORAGE
READ_PHONE_STATE

https://stackoverflow.com/a/60100728/3850012

**Comment by darshanclevertap** [comment]
@hvaughan3 Please check latest release v2.1.8. Thanks!

**Comment by hvaughan3** [comment]
I think that fixed it. Thank you very much for the quickness!
