### ISSUE TITLE
Push notification symbol is showing in ios

### ISSUE THREAD

**Issue by NagendraMNK** [CleverTap/clevertap-cordova#52]
![image](https://user-images.githubusercontent.com/12828174/75372849-24707800-58ef-11ea-8242-c98af771208f.png)

I am sending "registerPush" on login and registration action and enabled push notification in Apple developer account same profile imported to Xcode, while opening app permission is coming to accept push notification but i am unable to receive or not enabled symbol in clevertap dashboard

**Comment by Aditi3** [comment]
Hi @NagendraMNK 

I quickly tested the Push Notifications on an iOS device and seems to be working correctly.
Could you please check and verify the integration at your end?

Also, do to check out our [Example Project](https://github.com/CleverTap/clevertap-cordova/tree/master/ExampleProject) to verify the integration.

Thank you.

**Comment by NagendraMNK** [comment]
same codebase (ionic 4 and angular) is working fine in Android, is there any other configuration or preference for iOS

Can you please help me on is there any different configs apart from the push notification certificate

**Comment by Aditi3** [comment]
HI @NagendraMNK 

I'm not sure which configuration you are missing in your project?

Can you share a demo project with us on support@clevertap.com where the Push Notifications are not working for you? 

We will take a look at it.

**Comment by NagendraMNK** [comment]
Hi @Aditi3 

Thank you for your replay, I was looking Ionic Angular using Cordova plugin

When i use registerPush method after platfrom ready, i am getting a promise to confirm and from that i need get the APNS token for iOS, 

Android FCM is coming through cordova plugin and working fine, iOS i need to get the token to push into setPushToken event

Should we use need to use any plugin for APN's token after promise accepted

**Comment by Aditi3** [comment]
Hi @NagendraMNK 

Can you navigate to your AppDelegate class and try calling CleverTap autoIntegrate in `application:didFinishLaunchingWithOptions:` method?

Helping code snippet: 

```
- (BOOL)application:(UIApplication*)application didFinishLaunchingWithOptions:(NSDictionary*)launchOptions
{
    self.viewController = [[MainViewController alloc] init];
    [CleverTap autoIntegrate];
    return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
```

Also, ensure to import the CleverTap header `#import <CleverTapSDK/CleverTap.h>` in your AppDelegate class.

**Comment by Aditi3** [comment]
Closing it, feel free to reopen if you need further help or you can also write to support@clevertap.com.
