### ISSUE TITLE
Is Native display supported on iOS and Android for cordova plugin?

### ISSUE THREAD

**Issue by giarauz** [CleverTap/clevertap-cordova#53]
We would like to implement native display on our ionic 4 projects.

**Comment by Aditi3** [comment]
Hi @giarauz 

Currently, Native Display is not supported in our Cordova Plugin. 

Please allow me some time to discuss this requirement with our Product Team and I will get back to you with an update shortly.

Thank you.

**Comment by darshanclevertap** [comment]
@giarauz Native Display will also be available with the next release. Stay tuned. Thanks!

**Comment by darshanclevertap** [comment]
@giarauz Native display is supported in v2.1.9 which is live now
