### ISSUE TITLE
Disable Personalization at Runtime

### ISSUE THREAD

**Issue by hvaughan3** [CleverTap/clevertap-cordova#54]
We call `enablePersonalization` on app start and we would now like to give users the ability to opt-out of personalization. The problem I see if that there is no way to pass `false` into `enablePersonalization` for example.

Is there any way to disable personalization at runtime? Thanks.

**Comment by darshanclevertap** [comment]
@hvaughan3 Thank you for bringing this to our notice, we do not have a `disablePersonalization` API exposed yet. We will get this included in the next version of the release.

I'd like to know your use case of using the `enablePersonalization` method so that I can suggest some work around for the time being.

**Comment by hvaughan3** [comment]
@darshanclevertap That would be great, thank you!

We call the enable method on app startup (see below). Our plan would be to provide a checkbox in the app that a user could click to either disable or re-enable personalization. We do plan to opt the user into personalization automatically and the user could then choose to opt-out (for CCPA) compliance. Thanks again.

    class MessagingUtil {
      static init () {
        if (window.hasOwnProperty('cordova')) {
          try {
            window.CleverTap.enablePersonalization()
          } catch (e) {
            // log it
          }
        }
      }
    }

**Comment by darshanclevertap** [comment]
@hvaughan3 Thanks you for pointing this out, we will add this in our next release.

**Comment by darshanclevertap** [comment]
@hvaughan3 This has been added in v2.1.9 which is live now
