### ISSUE TITLE
plugin.xml config-file tag

### ISSUE THREAD

**Issue by giarauz** [CleverTap/clevertap-cordova#55]
HI guys, 

In order to integrate the plugin i had to remove the following tag from plugin.xml and do the whitelisting inside our own config.xml.
<config-file>
 <access origin="*.wzrkt.com" />
</config-file>

According to the Cordova documentation, if the tag does not contain the target attribute this is ignored by cordova and in my case that I use continuous integration it generates an error.

config file undefined requested for changes not found at /myapp/cordova/platforms/android/undefined, ignoring

**Comment by darshanclevertap** [comment]
@giarauz What did you remove from the plugin.xml?

**Comment by giarauz** [comment]
I remove  these lines on android and ios 

		<config-file>
			<access origin="*.wzrkt.com" />
		</config-file>

**Comment by darshanclevertap** [comment]
@sagrawal31 @giaruz This will be fixed with the next release. Stay tuned.

**Comment by sagrawal31** [comment]
Roger that @darshanclevertap

**Comment by darshanclevertap** [comment]
@giarauz @sagrawal31 this has been fixed in v2.1.9 which is live now

**Comment by sagrawal31** [comment]
Thanks @darshanclevertap
