### ISSUE TITLE
Plugin conflicting with Firebase plugins

### ISSUE THREAD

**Issue by sagrawal31** [CleverTap/clevertap-cordova#58]
# Description

Wondering, if this CleverTap Cordova plugin works with Firebase plugins? 

I'm using the latest versions of:

1. https://github.com/chemerisuk/cordova-plugin-firebase-messaging
2. https://github.com/chemerisuk/cordova-plugin-firebase-analytics
3. https://github.com/chemerisuk/cordova-plugin-firebase-crash

Our build without this plugin is working fine but as soon as, we are installing this one, we are getting the following errors:

```
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:injectCrashlyticsMappingFileIdDebug
> Task :app:writeDebugApplicationId

> Task :app:processDebugGoogleServices
Parsing json file: /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/google-services.json

> Task :app:mergeDebugResources FAILED
[string/google_app_id] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/src/main/res/values/strings.xml	[string/google_app_id] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/build/generated/res/google-services/debug/values/values.xml: Error: Duplicate resources
[string/google_api_key] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/src/main/res/values/strings.xml	[string/google_api_key] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/build/generated/res/google-services/debug/values/values.xml: Error: Duplicate resources

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> [string/google_app_id] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/src/main/res/values/strings.xml	[string/google_app_id] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/build/generated/res/google-services/debug/values/values.xml: Error: Duplicate resources
  [string/google_api_key] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/src/main/res/values/strings.xml	[string/google_api_key] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/build/generated/res/google-services/debug/values/values.xml: Error: Duplicate resources

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
23 actionable tasks: 23 executed
/Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> [string/google_app_id] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/src/main/res/values/strings.xml	[string/google_app_id] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/build/generated/res/google-services/debug/values/values.xml: Error: Duplicate resources
  [string/google_api_key] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/src/main/res/values/strings.xml	[string/google_api_key] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/build/generated/res/google-services/debug/values/values.xml: Error: Duplicate resources

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
```

We have been trying hard on this issue for the last 4 days but couldn't get it functional. We even looked at the issues of this plugin but couldn't find anything related exception [this](https://github.com/CleverTap/clevertap-cordova/issues/15).

I know this is something related to `google-services.json` file which is being copied two times. One is being used by `after plugin install hook` and other is being copied by our `config.xml` i.e. `<resource-file src="google-services.json" target="app/google-services.json" />` which is required for Cordova Firebase plugin.

# Environment

```bash
Ionic:

   Ionic CLI          : 6.5.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.3, (and 24 other plugins)

Utility:

   cordova-res (update available: 0.13.0) : 0.5.1
   native-run (update available: 1.0.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/shashank/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v10.16.0 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.2.1 Build version 11B500
```

**Comment by sagrawal31** [comment]
## Summary of our last 3 days of research & debugging

We saw that this plugin also uses `com.google.firebase:firebase-messaging` so we tried to remove the `cordova-plugin-firebase-messaging` plugin. Which resulted in `firebase-iid` dependency mismatch followed by some other.

Then we tried to tweak the two version of `google-services.json` file but removing one location of those fails the other.

**Comment by sagrawal31** [comment]
Updated the environment information.

**Comment by sagrawal31** [comment]
@darshanclevertap any update here? This is a blocker for us.

**Comment by darshanclevertap** [comment]
@sagrawal31 

v2.1.9 is live.

You can use Firebase Cloud Messaging version using the following command -

```
cordova plugin add https://github.com/CleverTap/clevertap-cordova.git 
--variable CLEVERTAP_ACCOUNT_ID="ACCOUNT_ID" 
--variable CLEVERTAP_TOKEN="ACCOUNT_TOKEN" 
--variable FIREBASE_MESSAGING_VERSION="20.1.+"
```
Please note, using FCM v18 and above will make Android use Android support libs, please add the following two lines in your `gradle.properties` file -

```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by sagrawal31** [comment]
That's great @darshanclevertap 

I'll test out this.

**Comment by sagrawal31** [comment]
@darshanclevertap I'm still getting the error

```
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:injectCrashlyticsMappingFileIdDebug
> Task :app:writeDebugApplicationId

> Task :app:processDebugGoogleServices
Parsing json file: /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/google-services.json

> Task :app:mergeDebugResources FAILED
[string/google_app_id] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/src/main/res/values/strings.xml	[string/google_app_id] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/build/generated/res/google-services/debug/values/values.xml: Error: Duplicate resources
[string/google_api_key] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/src/main/res/values/strings.xml	[string/google_api_key] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/build/generated/res/google-services/debug/values/values.xml: Error: Duplicate resources

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> [string/google_app_id] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/src/main/res/values/strings.xml	[string/google_app_id] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/build/generated/res/google-services/debug/values/values.xml: Error: Duplicate resources
  [string/google_api_key] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/src/main/res/values/strings.xml	[string/google_api_key] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/build/generated/res/google-services/debug/values/values.xml: Error: Duplicate resources

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
23 actionable tasks: 23 executed
/Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> [string/google_app_id] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/src/main/res/values/strings.xml	[string/google_app_id] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/build/generated/res/google-services/debug/values/values.xml: Error: Duplicate resources
  [string/google_api_key] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/src/main/res/values/strings.xml	[string/google_api_key] /Users/shashank/Projects/onmobile/kids-app/mobile-app/platforms/android/app/build/generated/res/google-services/debug/values/values.xml: Error: Duplicate resources

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
```

Please reopen this issue.

**Comment by sagrawal31** [comment]
Although, after various iterations, I was able to pass the build and run the code. Basically, I commented out the code https://github.com/CleverTap/clevertap-cordova/blob/2.2.0/scripts/androidAfterPluginAdd.js#L38..L62 which actually modifying `platforms/android/app/src/main/res/values/strings.xml`.

May I know if the above lines L38..L62 are actually required.

**Comment by darshanclevertap** [comment]
@sagrawal31 You're getting the build error when you're using `cordova-plugin-firebase-messaging` along with CleverTap?

**Comment by darshanclevertap** [comment]
@sagrawal31 Give me some time, I will get back to you on this.

**Comment by darshanclevertap** [comment]
@sagrawal31 The lines do the following -

* It reads from either of the 2 files (`google-services.json` , `platforms/android/assets/www/google-services.json`) and writes the contents to the following file: `platforms/android/google-services.json`
* Updates the `google_app_id` and `google_api_key` in `platforms/android/app/src/main/res/values/strings.xml` file with `mobilesdk_app_id` and `current_key` values present in above JSON files.

Since we set the Firebase version in `build.gradle` to ensure an out-of-the-box experience, we assume that `google_app_id` and `google_api_key` are not present in `strings.xml` and we copy it manually using the script.

Since you're using the `cordova-plugin-firebase-messaging` plugin, I think they're doing it too and hence a Duplicate Resources error is being thrown. I'd suggest you proceed by commenting out the code as we cannot remove this code from the script right now.

**Comment by sagrawal31** [comment]
> You're getting the build error when you're using cordova-plugin-firebase-messaging along with CleverTap?

Yes.

> The lines do the following

Yes, that I understood already since the first creation of the issue. What I meant is that whether those lines are required. Which you answered later.  But I don't think so `cordova-plugin-firebase-messaging` is doing something similar. I checked their code.

If you look closely, the task `Task :app:processDebugGoogleServices` followed by `Task :app:mergeDebugResources` is actually failing which seems to be internal from **Google Services Gradle Plugin**.

**Comment by sagrawal31** [comment]
And actually, as per my understanding, you don't need to manually set those two variables in `strings.xml` (that is being done by hook script) as the Google services plugin will already do it for you-

- https://developers.google.com/android/guides/google-services-plugin#processing_the_json_file
- https://github.com/firebase/quickstart-android/issues/458#issuecomment-376194813

So the SDK should automatically pick the `google_app_id` & `google_api_key` because the Google services plugin is producing the `strings.xml` at compile time.

On the 2nd thought, the hook script in this plugin is by default using the first client (at 0th index) i.e. `jsonContents.client[0].client_info` which is also wrong because if you configure multiple apps in Firebase and when you download the `google-services.json` files, it is not compulsory that the required package id of my app will be present at 0th index i.e. `client[0]`.

While if you remove that and use the variables from already present variables, Google plugin will make sure that you get the correct client info of the same bundle id as of my app.

**Comment by sagrawal31** [comment]
@darshanclevertap any update here?

I did the workaround temporarily by adding the following script to my app using `before_build` script.

```js
/**
 * https://github.com/CleverTap/clevertap-cordova/issues/58#issuecomment-631262884
 */
function fixDuplicateVariables() {
    const path = "platforms/android/app/src/main/res/values/strings.xml";
    let s = fs.readFileSync(path).toString();

    s = s.replace(new RegExp('<string name="google_app_id">([^\@<]+?)<\/string>', "i"), '');
    s = s.replace(new RegExp('<string name="google_api_key">([^\@<]+?)<\/string>', "i"), '');
    s = s.replace(new RegExp('(\r\n|\n|\r)[ \t]*(\r\n|\n|\r)', "gm"), '$1');

    fs.writeFileSync(path, s);
}
```

I took the code this plugin itself and reversed it but I'm still curious.

**Comment by sagrawal31** [comment]
Any update here?

**Comment by darshanclevertap** [comment]
@sagrawal31 Sorry, I've been caught up with other stuff, I will take a fresh look into this and let you know in a few days.

**Comment by sagrawal31** [comment]
Okay. I'll be waiting.

**Comment by sagrawal31** [comment]
Awaiting response from Cordova Team @darshanclevertap

**Comment by darshanclevertap** [comment]
@sagrawal31 I integrated `clevertap-cordova`, `cordova-plugin-firebase-messaging` and `cordova-support-google-services` in a brand new Cordova project. As you mentioned, I got the following error - 

```
What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> [string/google_api_key] /Users/darshan/Desktop/CleverTapApps/Cordova/HelloCordova/platforms/android/app/build/generated/res/google-services/debug/values/values.xml	[string/google_api_key] /Users/darshan/Desktop/CleverTapApps/Cordova/HelloCordova/platforms/android/app/src/main/res/values/strings.xml: Error: Duplicate resources
  [string/google_app_id] /Users/darshan/Desktop/CleverTapApps/Cordova/HelloCordova/platforms/android/app/build/generated/res/google-services/debug/values/values.xml	[string/google_app_id] /Users/darshan/Desktop/CleverTapApps/Cordova/HelloCordova/platforms/android/app/src/main/res/values/strings.xml: Error: Duplicate resources
```
Now as you rightly said this is because of our `androidAfterPluginAdd.js` hook script. But as I mentioned above we need this because we provide Firebase Cloud Messaging as an out-of-the-box experience. So I tried to find a middle ground where you can avoid the build error. I stumbled upon this [FAQ link](https://github.com/chemerisuk/cordova-support-google-services#faq) by the `cordova-support-google-services` plugin. I removed the `google_app_id` and `google_api_key` as mentioned from `platforms/android/app/src/main/res/values/strings.xml` and the build was successful. Every subsequent build was also successful so this is a one time fix whenever you add the CleverTap Cordova plugin.

Now I know this is not the ideal way, but to fix this entirely we will have to modify our out-of-the-box experience for Firebase Cloud Messaging by modifying our hook script to not add the values to `strings.xml` or completely remove the firebase option and let app developers figure out using firebase services on their own. 

This is a decision for our Product Team so my suggestion is to live with the workaround of removing the `google_app_id` and `google_api_key` keys manually and building it for now or you can fork our project and remove the part of the hook script which does this change.

I will update you when we take any decision regarding this.
Thank you for your patience.

**Comment by sagrawal31** [comment]
Hi @darshanclevertap 

Thanks for the detailed update. But I think you missed my above [comment](https://github.com/CleverTap/clevertap-cordova/issues/58#issuecomment-632032367). The approach that you took, I'm already doing it via a hook in my app itself. And the build is working fine for me.

But probably because of that we are not able to receive a push notification on the app. We are trying to send push notification from CleverTap portal using these two ids but none of them didn't work-

1. FCM token
2. CleverTap user id

Can you please confirm if you are able to receive push notification?

**Comment by darshanclevertap** [comment]
@sagrawal31 Have you added CleverTap's `FcmMessageListenerService` Service in the `AndroidManifest.xml` or are you relying on the `cordova-plugin-firebase-messaging` methods to receive the push?

**Comment by sagrawal31** [comment]
No @darshanclevertap we haven't added any such thing in `AndroidManifest.xml`. My thoughts-

1. Why would we (as the app developer) do it? Isn't that should come configured from this Cordova plugin itself?
2. Even there is some similar stuff to do, I couldn't find it in the documentation.

Your thoughts, please!

**Comment by darshanclevertap** [comment]
@sagrawal31 Yes, my bad, this `FcmMessageListenerService ` is added by the plugin. And `cordova-plugin-firebase-messaging` also adds their `FirebaseMessagingPluginService` in the `AndroidManifest.xml`

Maybe that is why you're not receiving the Push notifications. Please remove the `FcmMessageListenerService` and `FcmTokenListenerService` from your `AndroidManifest.xml` so that there is no conflict as to which Service will render the push notification. These two services are by CleverTap but I'm assuming you want to use the other firebase plugin

**Comment by darshanclevertap** [comment]
@sagrawal31 I have raised this issue internally with my team, but for now, we are not changing anything. I'm closing this issue. I will re-open this when we have some updates regarding this.

**Comment by sagrawal31** [comment]
Hi @darshanclevertap 

Apologies for the delayed reply (looked like) but I actually posted an update on 12th June which seems could not get delivered to you (because of my internet issue) and I was assuming that you are working on it until yesterday.

Coming to the issue, I removed the `by.chemerisuk.cordova.firebase.FirebaseMessagingPluginService` service and kept the CleverTap one (basically wanting to use CleverTap notifications) and tried to send the notification but that too didn't work. 

To debug the issue, I created a fresh Cordova app and only added the CleverTap Cordova plugin. I got the CleverTap profile id but it says that it is not registered for push (even after calling `CleverTap.registerPush()`).

**Comment by sagrawal31** [comment]
On second thought, can we say that either we will be able to send notifications via Firebase or via CleverTap?

**Comment by darshanclevertap** [comment]
@sagrawal31 Sorry, I just saw these right now. `CleverTap.registerPush()` is to register for Push Notifications in iOS. For Android, since you're no longer using `FirebaseMessagingPluginService `, I'd suggest downgrading the FCM library to 17.3.3 and adding our `FCMMessageListenerService` and `FCMTokenListenerService` in your `AndroidManifest.xml`.

Technically, you can send PNs via both since CleverTap also uses Firebase internally, but you will have to follow [the CleverTap payload](https://developer.clevertap.com/docs/android#section-custom-android-push-notifications-handling) to send Push Notifications as you'll be using our Service to render the Push Notification

**Comment by sagrawal31** [comment]
> I'd suggest downgrading the FCM library to 17.3.3

May I know the reason of this please? Because, although I removed `FirebaseMessagingPluginService` but that Firebase plugin still exists. 

> Technically, you can send PNs via both 

Both the services (one from Firebase another from CleverTap) listen for `<action android:name="com.google.firebase.MESSAGING_EVENT" />` so I was curious if both can be defined there.

> To debug the issue, I created a fresh Cordova app and only added the CleverTap Cordova plugin

Any update on this part? PN not working for me for fresh Cordova app.

**Comment by sagrawal31** [comment]
Can we reopen it.

**Comment by darshanclevertap** [comment]
@sagrawal31 This is a separate issue. I'd suggest you write to support@clevertap.com as we'll be able to help you in a faster way. You can mention this Github issue so that the support team has some context.

**Comment by sagrawal31** [comment]
A separate issue for "not receiving push notification" on plain Cordova app?

**Comment by darshanclevertap** [comment]
@sagrawal31 This thread has already gone from being about conflicting with a third party Firebase plugin to not receiving a push notification. I'm asking you to reach out to our support team because they will be able to you in a quicker way as they dedicatedly handle such issues.

**Comment by sagrawal31** [comment]
Got your point @darshanclevertap. Thanks for the efforts, really appreciate this.
