### ISSUE TITLE
ios 10 CleverTap.registerPush(); not working

### ISSUE THREAD

**Issue by roshan-shelar** [CleverTap/clevertap-cordova#6]
not able to register push notification in ios 10 
on clevertap dashboard device token is blank

**Comment by pwilkniss** [comment]
@roshan-shelar   not seeing any issues with registering for push in iOS10 using Cordova 6.3.1.

Please make sure your push notification entitlements are configured for your project in Xcode (  Your Target ->Capabilities->Push Notifications) and that you are calling CleverTap.registerPush in your JS after onDeviceReady.  

If you have further issues, please drop a note to support@clevertap.com with your account details and info on your setup and we will be glad to help you there.
