### ISSUE TITLE
Make Android dependencies configurable using Cordova plugin variables

### ISSUE THREAD

**Issue by sagrawal31** [CleverTap/clevertap-cordova#61]
# Description

This is a must-have feature because CleverTap team can't be bugged just for upgrading a few dependencies to the latest.

For example, as of [2.1.8](https://github.com/CleverTap/clevertap-cordova/blob/2.1.8/plugin.xml), the `com.clevertap.android:clevertap-android-sdk` is `3.6.4` while we already have the latest updates for CleverTap Android SDK with major crash fixes.

Same goes for others like `firebase-messaging` plugin (which I think is the cause of #58).

For example:

```
cordova plugin add https://github.com/CleverTap/clevertap-cordova.git 
    --variable CLEVERTAP_ACCOUNT_ID="YOUR CLEVERTAP ACCOUNT ID" 
    --variable CLEVERTAP_TOKEN="YOUR CELVERTAP ACCOUNT TOKEN"
    --variable CLEVERTAP_SDK_VERSION="3.7.2"
    --variable FIREBASE_MESSAGING_SDK_VERSION="20.1.+"
```

**Comment by darshanclevertap** [comment]
Hi @sagrawal31 We're going through your issues one by one, I just thought I will reply here so that you don't feel we're ignoring you. We haven't updated our Cordova SDK for a long time and we have a lot of new features present in the native SDK which will soon be a part of the Cordova SDK as well. Apart from the new features, we will be incorporating fixes for some of the issues you've raised here. So thank you for your patience and stay tuned for more updates. Thanks!

**Comment by sagrawal31** [comment]
Hi, @darshanclevertap 

Thank you for a detailed writeup and update about your upcoming release. I appreciate this 😊

Looking for the release.

**Comment by darshanclevertap** [comment]
@sagrawal31 We are adding the Firebase Messaging version as a variable but if you move to FCM version 18 and above, you will have to use jetifier to convert our Android libs to AndroidX as CleverTap SDK has not migrated to AndroidX yet

**Comment by darshanclevertap** [comment]
@sagrawal31 Also we won't be adding a separate plugin variable for the SDK version as we always try and keep the underlying CleverTap SDKs at the latest version.

**Comment by darshanclevertap** [comment]
@sagrawal31 

v2.1.9 is live.

You can use Firebase Cloud Messaging version using the following command -

```
cordova plugin add https://github.com/CleverTap/clevertap-cordova.git 
--variable CLEVERTAP_ACCOUNT_ID="ACCOUNT_ID" 
--variable CLEVERTAP_TOKEN="ACCOUNT_TOKEN" 
--variable FIREBASE_MESSAGING_VERSION="20.1.+"
```
Please note, using FCM v18 and above will make Android use Android support libs, please add the following two lines in your `gradle.properties` file - 
```
android.useAndroidX=true
android.enableJetifier=true
```
