### ISSUE TITLE
Android build failure because of typo in CleverTapPlugin.java

### ISSUE THREAD

**Issue by sagrawal31** [CleverTap/clevertap-cordova#66]
# Description

A typo causing build failure in Android https://github.com/CleverTap/clevertap-cordova/blob/2.2.0/src/android/CleverTapPlugin.java#L1342.

# Solution

Change `ssetendPluginResult` to `sendPluginResult`.

# Suggestion

Setup GitHub actions & CI and test the basic functionality of the plugins so that this kind of errors can be avoided because bugs like this can't be expected from CleverTap team 🙂

**Comment by darshanclevertap** [comment]
@sagrawal31 This will be fixed asap. I'm surprised how this wasn't caught in a simple build. Thank you for your suggestion, we are working in the coming on setting up Testing and CI for all our repos in the coming months.

**Comment by sagrawal31** [comment]
No worries, @darshanclevertap things happen! 😄

**Comment by darshanclevertap** [comment]
@sagrawal31 v2.2.1 fixes this. thanks!

**Comment by sagrawal31** [comment]
Thanks @darshanclevertap for quick fix.
