### ISSUE TITLE
Better Docmentation

### ISSUE THREAD

**Issue by brayn003** [CleverTap/clevertap-cordova#7]
Clevertap surely provides a lot of useful tools.
Unfortunately, the documentation for the cordova plugin is incomplete. And I am having a hard time figuring out how to utilize it. Can we have a better documentation for this?

E.g.
- I need to app UTM tracking in my android app
- How do I pass additional parameters while creating profiles?
- Is there a way to handle deeplinks for android?

The current documentation provides absolutely no info about it.
I do see functionalities mentioned in the starter app repository. But they are not at all documented.
I would appreciate it if your team looks into it

**Comment by pwilkniss** [comment]
@brayn003 sorry you're having trouble here.  Please email support at clevertap.com anytime with specific questions/issues and also re: any documentation issues/suggestions.  Our team is super responsive on that support channel.

As to your questions:
UTM tracking is done automatically for incoming deep links (see below).  You can also manually record an install referrer:
// Call this to manually track the utm details for an incoming install referrer.
// source = string               the utm source
// medium = string               the utm medium
// campaign = string             the utm campaign
CleverTap.prototype.pushInstallReferrer = function (source, medium, campaign) {
    cordova.exec(null, null, "CleverTapPlugin", "pushInstallReferrer", [source, medium, campaign]);
}
e.g. CleverTap.pushInstallReferrer("androidsource", "androidmedium", "androidcampaign");

Deep links:
1. Register an intent filter for your deep link scheme in your AndroidManifest.xml.  

<activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.Black.NoTitleBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            **<intent-filter android:label="@string/app_name">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="clevertapstarter" />**
            </intent-filter>
        </activity>

2. Bind to the "onDeepLink" event in your index.js:
 bindEvents: function() {
document.addEventListener('onDeepLink', this.onDeepLink, false);
...
}

 // deep link handling
    onDeepLink: function(e) {
        console.log(e.deeplink);
    },


You can pass custom profile variable primitives in the object argument to CleverTap.profileSet.
e.g. CleverTap.profileSet({"Identity":"a12345678","custom12":1.311});

If you need further help with any of this please feel free to email support at clevertap.com anytime.
