### ISSUE TITLE
Update documentation about the key parts of notification channel for Android 9+

### ISSUE THREAD

**Issue by sagrawal31** [CleverTap/clevertap-cordova#70]
This is exact copy of https://github.com/CleverTap/clevertap-android-sdk/issues/89 but required here because most Cordova developer won't go to the native SDK to read the documentation.

**Comment by darshanclevertap** [comment]
@sagrawal31 Hey, thank you for the feedback, we will incorporate this into our README and our official [Cordova documentation](https://developer.clevertap.com/docs/cordova) as well.

**Comment by Sidd27** [comment]
Any updates?
