### ISSUE TITLE
Support of Android SDK v4.0.0

### ISSUE THREAD

**Issue by sagrawal31** [CleverTap/clevertap-cordova#72]
CT Android SDK v4.0.0 release contains various improvements and bug fixes as given here https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md

It will be better if Cordova wrapper can support it.

**Comment by stevecarlton** [comment]
Agreed, thank you @sagrawal31 for creating this issue as we need to get our apps updated ASAP!

**Comment by darshanclevertap** [comment]
Hey, @sagrawal31 & @stevecarlton 

Yes, we're working on it as I type this, you can expect an update by 15th October.

**Comment by sagrawal31** [comment]
Thank you @darshanclevertap for the prompt response. Awaiting the new plugin version!

**Comment by darshanclevertap** [comment]
@stevecarlton @sagrawal31 CleverTap Cordova SDK v2.3.0 has been released with support for CleverTap Android SDK v4.0.0. Please read the [AndroidX](https://github.com/CleverTap/clevertap-cordova#support-androidx) part of the documentation. Also, the default firebase messaging version has been increased to v20.2.4

**Comment by sagrawal31** [comment]
Thank you so much @darshanclevertap for getting it through.
