### ISSUE TITLE
Huawei Push Service

### ISSUE THREAD

**Issue by malua** [CleverTap/clevertap-cordova#85]
Hey,

I saw in the code that you can set the huawei push token? but there is no documentation or at least i can't find it.

Could you point me in the right direction on how to use this plugin with huawei push?

thank you very much!

**Comment by darshanclevertap** [comment]
@malua You can find the Android documentation for [Huawei Push here](https://developer.clevertap.com/docs/clevertap-huawei-push-integration). Please note that we do not have direct support in our Cordova SDK for the same at the moment. You will have to integrate this by yourself on the Android side.

**Comment by darshanclevertap** [comment]
@malua I hope the documentation helped. Closing this for now

**Comment by malua** [comment]
Thanks for your help!
