### ISSUE TITLE
Clevertap push

### ISSUE THREAD

**Issue by nielsvandenboogaart** [CleverTap/clevertap-cordova#9]
When initiating a test push from the clevertap dashboard the push doesn't pop-up on phone.
Tho, I am able to catch the push from the app using the phonegap-plugin-push plugin. (even though no notification is shown)

**Comment by pwilkniss** [comment]
@nielsvandenboogaart you're going to run into problems trying to have more than one plugin handle push notifications for you in Android.  Without writing additional custom native code, you can really only have one plugin listening/rendering notifications.  Feel free to email support at clevertap.com if you need further help.
