### ISSUE TITLE
Optimistic Pod Version Causing Build Failures

### ISSUE THREAD

**Issue by hvaughan3** [CleverTap/clevertap-cordova#94]
Our builds suddenly started failing when building in Xcode, stating that `CleverTap+ABTesting.h` could not be found. After looking around everywhere, I noticed that CT iOS SDK 3.9.3 removed that functionality.

It looks like in this plugin's plugin.xml, `~> 3.9.2` is being used for the pod version, which will automatically update to 3.9.3 if that pod is available, from my limited understanding. I think that should be changed to the following so that it is pinned to an exact version.

    <framework src="CleverTap-iOS-SDK" type="podspec" spec="3.9.2" />

**Comment by Aditi3** [comment]
Thank you @hvaughan3. We will definitely consider the improvement highlighted by you in our next release.

At present, you can edit the CleverTap pod dependency to `pod 'CleverTap-iOS-SDK', '3.9.2'` to resolve the error.

**Comment by hvaughan3** [comment]
Thank you for the response. I decided to fork the library for now since our CI/CD pipeline requires everything to be done in code. I appreciate your help.
